name: shelf
version: 0.1.0
author: Kevin Moore <kevmoo@google.com>
description: Web Server Middleware for Dart
homepage: https://github.com/kevmoo/shelf.dart
environment:
  sdk: '>=1.3.0-dev <2.0.0'
dependencies:
  collection: '>=0.9.1 <0.10.0'
  mime: '>=0.9.0 <0.10.0'
  path: '>=1.0.0 <2.0.0'
  stack_trace: '>=0.9.2 <0.10.0'
dev_dependencies:
  hop: '>=0.30.0 <0.31.0'
  hop_docgen: '>=0.1.1 <0.2.0'
  http: '>=0.9.2 <0.10.0'
  scheduled_test: '>=0.10.0 <0.11.0'
  unittest: '>=0.10.0 <0.11.0'
